# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fishName', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('fishName',),
            },
        ),
        migrations.CreateModel(
            name='FishDetachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detachment', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('detachment',),
            },
        ),
        migrations.CreateModel(
            name='FishFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('feature',),
            },
        ),
        migrations.CreateModel(
            name='FishKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('kind',),
            },
        ),
        migrations.AddField(
            model_name='fish',
            name='detachments',
            field=models.ManyToManyField(blank=True, null=True, to='main.FishDetachment'),
        ),
        migrations.AddField(
            model_name='fish',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, to='main.FishFeature'),
        ),
        migrations.AddField(
            model_name='fish',
            name='kinds',
            field=models.ManyToManyField(blank=True, null=True, to='main.FishKind'),
        ),
    ]
