# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishdetachment',
            name='features',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='main.FishFeature'),
        ),
        migrations.AddField(
            model_name='fishdetachment',
            name='kinds',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='main.FishKind'),
        ),
    ]
