# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171001_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishkind',
            name='features',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='main.FishFeature'),
        ),
    ]
